/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package employees;

import org.junit.Test;
import static org.junit.Assert.*;

public class EmployeeAplicationTest {
    @Test public void testSomeLibraryMethod() {
    	EmployeeAplication classUnderTest = new EmployeeAplication();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
