# [Services]
apiVersion: v1
kind: Service
metadata:
  name: employees-be-svc
spec:
  ports:
  - port: 8081
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: employees-be
    tier: backend
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees-be
  template:
    metadata:
      labels:
        app: employees-be
        tier: backend
    spec:
      containers:
      # [APP]
      - name: employees-be
        image: gcr.io/prueba-moises-gcp/employees-be:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "500Mi"
          limits:
            cpu: "200m"
            memory: "1000Mi" 
        livenessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 160
          periodSeconds: 60
          timeoutSeconds: 10       
        #[env-vars]
        env:
        - name: SFTP_HOST
          value: "35.184.121.73"
        - name: SFTP_USER  
          value: "moises"
        - name: SFTP_PSWD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: pswd