/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package employees;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class EmployeeAplication {
    
	public static void main(String[] args) {
	    SpringApplication.run(EmployeeAplication.class, args);
	  }

	public boolean someLibraryMethod() {
		return true;
	}
	
}
